#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

apt-get update
apt-get install -y nginx
echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://blog.larryacademy.tech;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
